// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC82pQODXt78aV7VT65QVif9sKoT7BIe-g',
    appId: '1:279153784343:web:9fe71cb3e3ae1bbf778e52',
    messagingSenderId: '279153784343',
    projectId: 'login_register',
    authDomain: 'login_register.firebaseapp.com',
    storageBucket: 'login_register.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcnBWvPJZ8xvEUeFukyIJEy2sQ6wv42C4',
    appId: '1:279153784343:android:843619aab076f7c2778e52',
    messagingSenderId: '279153784343',
    projectId: 'login_register',
    storageBucket: 'login_register.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9nE1guZ8zrAHq3SCqghwVqIpjb5KNUaI',
    appId: '1:279153784343:ios:77996655cc2a6208778e52',
    messagingSenderId: '279153784343',
    projectId: 'login_register',
    storageBucket: 'login_register.appspot.com',
    iosClientId:
        '279153784343-dgqd12bdlu928enfbkd4i17hciqhe8es.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9nE1guZ8zrAHq3SCqghwVqIpjb5KNUaI',
    appId: '1:279153784343:ios:77996655cc2a6208778e52',
    messagingSenderId: '279153784343',
    projectId: 'login_register',
    storageBucket: 'login_register.appspot.com',
    iosClientId:
        '279153784343-dgqd12bdlu928enfbkd4i17hciqhe8es.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
